# <center>Python Functions<center/> 

To make the output look attractive
we use the str.format() method.
This method is visible to any string object.

In [63]:
""" Define a function which counts vowels and consonant in a word."""
# Write code here

def takestr(str):
    vowel_Count=0
    consonant_count=0
    for i in range(0,len(str)):
        if str[i]=="a" or str[i]=="e" or str[i]=="i" or str[i]=="o" or str[i]=="u" or str[i]=="A" or str[i]=="E"or str[i]=="I"or str[i]=="O"or str[i]=="U":
            vowel_Count=vowel_Count+1
        else:
            consonant_count=consonant_count+1
    print("consonant count is ",consonant_count)
    print("vowel count is ",vowel_Count)

str=input("enter the string:")
takestr(str)


enter the string:hasrh
consonant count is  4
vowel count is  1


In [44]:
"""Write a function that takes in a string and returns the string with all the vowels
removed."""
# Write code here

import re
def remove_vowel(string):
    return (re.sub("[aeiouAEIOU]","",string))            
  
str=input("enter the string:")
print(remove_vowel(str))

enter the string:harsh
hrsh


In [12]:
"""Write a Python function that takes a list of integers as input and 
returns the maximum sum that can be obtained by adding any two numbers from the list.
The function should have a time complexity of O(n), where n is the length of the list."""
# Write code here

def max_sum_pair(lst):
    if len(lst) < 2:
        raise ValueError("Input list should contain at least two numbers.")

    max_sum = float('-inf')
    max_num = float('-inf')
    second_max = float('-inf')

    for num in lst:
        if num > max_num:
            second_max = max_num
            max_num = num
        elif num > second_max:
            second_max = num
    max_sum = max_num + second_max
    return max_sum


lst1=[]
n = int(input("Enter number of elements : "))
for i in range(0,n):
    ele = int(input())
    lst1.append(ele)
print("maximum sum that can be obtained by adding any two numbers from the list:",max_sum_pair(lst1))


Enter number of elements : 5
2
3
4
1
5
maximum sum that can be obtained by adding any two numbers from the list: 9


In [1]:
"""Write a function to find factorial of a number but also store the factorials calculated in a dictionary
as done in the Fibonacci series example."""
# Write code here


num = int(input("Enter a number: "))    
factorial = 1    
stor_dis={}
if num < 0:    
   print(" Factorial does not exist for negative numbers")    
elif num == 0:    
   print("The factorial of 0 is 1")    
else:    
    for i in range(1,num + 1): 
        c=factorial*i
        factorial = factorial*i
        stor_dis[i] = c
    print("The factorial of",num,"is",factorial)
    print("the factorials calculated in a dictionary",stor_dis)

Enter a number: 5
The factorial of 5 is 120
the factorials calculated in a dictionary {1: 1, 2: 2, 3: 6, 4: 24, 5: 120}


In [3]:
""". Write a function prodDigits() that inputs two numbers and returns the product and addition of this two number 
in the hexadecimal formate and also return the value in hexadecimal which stored on list"""
# Write code here

def prodDigits(a,b):
    c=a+b
    hex_val=hex(c)
    return hex_val

x=int(input("enter the number"))
y=int(input("enter the number"))
lst1=[(prodDigits(x,y))]
print("Addition of this two number in the hexadecimal",(prodDigits(x,y)))
print("the value in hexadecimal which stored on list",lst1)

enter the number6
enter the number5
Addition of this two number in the hexadecimal 0xb
the value in hexadecimal which stored on list ['0xb']


In [6]:
"""write a program in python function which return the  gausian transform in the form of array"""
# Write code here


import numpy as np
x, y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
arry = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print("gausian transform in the form of array")
print(arry)


gausian transform in the form of array
[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


In [14]:
"""Write a program with LAMBDA function to add values from two lists and create a new list."""
# Write code here

def Lambda_fun(n1,n2):
    return map(lambda x, y: x + y, n1, n2)

lst1=[1,2,3,4,5]
lst2=[1,2,3,4,5]
    
mydo = Lambda_fun(lst1,lst2)
lst3=list(mydo)
print("LAMBDA function to add values from two lists and create a new list",lst3)


LAMBDA function to add values from two lists and create a new list [2, 4, 6, 8, 10]


In [15]:
"""Write a Python program with LAMBDA functioon to find the value for (a-b)^3 using lambda"""
# Write code here

def Lambda_fun(n):
    return lambda a: (a-n)**3
a=int(input("enter the a:"))
b=int(input("enter the b:"))
mydo = Lambda_fun(b)
print('the value for (a-b)^3 using lambda',mydo(a))

enter the a:4
enter the b:2
the value for (a-b)^3 using lambda 8


In [3]:
"""Write a Python function to check whether a string is a pangram or not."""
# Write code here
def ispangram(str):
    all="abcdefghijklmnopqrstuvwxyz"
    for i in all:
        if i not in str.lower():
            c=0
        else:
            c=1    
    return c
            
str=input("Enter the string==")
v=ispangram(str)
if v==1:
    print("a string is a pangram ")
else:
    print("a string is not a pangram ")

Enter the string==The five boxing wizards jump quickly.
a string is a pangram 


In [7]:
"""Write a Python function that prints out the first n rows of Pascal's triangle."""
# Write code here
from math import factorial
 
n = int(input("enter the number"))
for i in range(n):
    for j in range(n-i+1):
        print(end=" ")
    for j in range(i+1):
        print(factorial(i)//(factorial(j)*factorial(i-j)), end=" ")
    print()

enter the number5
      1 
     1 1 
    1 2 1 
   1 3 3 1 
  1 4 6 4 1 


In [13]:
"""write a python lambda function which take farenhite as input and return celcius as output"""
# Write code here

def Lambda_fun(f):
    return lambda a: a+(5/9*(f-32))
f=int(input("enter the farenhite="))
mydo = Lambda_fun(f)
print("celcius",mydo(1))


enter the farenhite=98
celcius 37.66666666666667


In [17]:
"""write a python function which returns the prime number between -100-200 """
# Write code here

def prime_no(lower,upper):
    for num in range(lower, upper + 1):
        if num > 1:
            for i in range(2, num):
                if (num % i) == 0:
                    break
            else:
                print(num)

lower = 100
upper = 200

print("Prime numbers between", lower, "and", upper, "are:")
prime_no(lower,upper)


Prime numbers between 100 and 200 are:
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199


In [42]:
"""write a python function which takes a string sentence as input, which finds all the finds and stored these vowels 
in the list with there original position in the original sentence as the form of tuple like : [("a",1),("b",1),...]"""
# Write code here

def find_vowel(str):
    ele_lst=[]
    
    for i in range(0,len(str)):
        if str[i]=="a" or str[i]=="e" or str[i]=="i" or str[i]=="o" or str[i]=="u" or str[i]=="A" or str[i]=="E"or str[i]=="I"or str[i]=="O"or str[i]=="U":
            ele_lst.append((str[i],i))
    tup=tuple(ele_lst)
    print(tup)

str=input("enter the string:")
find_vowel(str)

enter the string:i am dastan_alam
(('i', 0), ('a', 2), ('a', 6), ('a', 9), ('a', 12), ('a', 14))


In [2]:
"""Write a Python program with function to reverse a string.And if the string contain any numerical value then
it should append at the last"""
# Write code here
import re

def check(str):
    check=str.isalnum()
    if check==True:
        onlynum=re.sub("[abcdefghijklmnopqrstvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ]","",str)
        onlyalp=re.sub("[0123456789]","",str)
        print(onlyalp[::-1]+onlynum)
        
str=input("enter the string:")
check(str)


enter the string:dastan7alam
malanatsad7


In [12]:
"""2. Write a program to print twin primes less than 2214. 
If two consecutive odd numbers are both prime then they are known as twin primes¶"""
# Write code here

def prime_no(n):
    for j in range(2, n):
        if (n % j) == 0:
            return False
    else:
        return True

def twin_prime(start,end):
    for i in range(start,end):
        j=i+2
        if (prime_no(i))and(prime_no(j)):
            print("{0} and {1}".format(i,j))
print("twin primes less than 2214:")
twin_prime(2,2214)

twin primes less than 2214:
3 and 5
5 and 7
11 and 13
17 and 19
29 and 31
41 and 43
59 and 61
71 and 73
101 and 103
107 and 109
137 and 139
149 and 151
179 and 181
191 and 193
197 and 199
227 and 229
239 and 241
269 and 271
281 and 283
311 and 313
347 and 349
419 and 421
431 and 433
461 and 463
521 and 523
569 and 571
599 and 601
617 and 619
641 and 643
659 and 661
809 and 811
821 and 823
827 and 829
857 and 859
881 and 883
1019 and 1021
1031 and 1033
1049 and 1051
1061 and 1063
1091 and 1093
1151 and 1153
1229 and 1231
1277 and 1279
1289 and 1291
1301 and 1303
1319 and 1321
1427 and 1429
1451 and 1453
1481 and 1483
1487 and 1489
1607 and 1609
1619 and 1621
1667 and 1669
1697 and 1699
1721 and 1723
1787 and 1789
1871 and 1873
1877 and 1879
1931 and 1933
1949 and 1951
1997 and 1999
2027 and 2029
2081 and 2083
2087 and 2089
2111 and 2113
2129 and 2131
2141 and 2143
